// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Verbenium.server.Data;

#nullable disable

namespace Verbenium.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614165959_RemoveUsesSprite")]
    partial class RemoveUsesSprite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Verbenium.server.Game.GameAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameNodeId");

                    b.ToTable("GameActions");
                });

            modelBuilder.Entity("Verbenium.server.Game.GameNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameNodes");
                });

            modelBuilder.Entity("Verbenium.server.Game.GameObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DefaultHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("DefaultWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameObjects");
                });

            modelBuilder.Entity("Verbenium.server.Game.GameObjectPlacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL");

                    b.Property<double?>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GameNodeId");

                    b.HasIndex("GameObjectId");

                    b.ToTable("GameObjectPlacements");
                });

            modelBuilder.Entity("Verbenium.server.Game.GameAction", b =>
                {
                    b.HasOne("Verbenium.server.Game.GameNode", null)
                        .WithMany("Actions")
                        .HasForeignKey("GameNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Verbenium.server.Game.GameObjectPlacement", b =>
                {
                    b.HasOne("Verbenium.server.Game.GameNode", "Node")
                        .WithMany("Placements")
                        .HasForeignKey("GameNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verbenium.server.Game.GameObject", "Object")
                        .WithMany("Placements")
                        .HasForeignKey("GameObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Verbenium.server.Game.GameNode", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Placements");
                });

            modelBuilder.Entity("Verbenium.server.Game.GameObject", b =>
                {
                    b.Navigation("Placements");
                });
#pragma warning restore 612, 618
        }
    }
}
